// <auto-generated />
namespace WFH.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddDayAtHomeAccount : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207221736592_AddDayAtHomeAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1azW7cNhC+F+g7CDq1BbKynRxSY53A9U9ipP6B5aRHg5Zm10QpUhEpY/fZeugj9RU6klaURP1R63UT9LaShsOZb4Yzw8/+56+/5+9XEXOeIJFU8CN3f7bnOsADEVK+PHJTtXj11n3/7scf5mdhtHK+lHKvMzlcyeWR+6hUfOh5MniEiMhZRINESLFQs0BEHgmFd7C396u3v+8BqnBRl+PMb1OuaAT5Az6eCB5ArFLCLkUITG7e4xc/1+pckQhkTAI4cv84/zgrpFznmFGCFvjAFq4Tvzn8LMFXieBLPyaKEna3jgG/LwiTsLH3MH5ja/LeQWayRzgXCtUJvpXLrnYG3TlDt9U6Myt36cg9Jetj9VFEUBdDwU+wbrzAVzeJiCFR61tYbBZfnLqO11znmQv1stqabH/8xdXrA9e5ShkjDww0TIijr0QCH4BDQhSEN0QpSDDqFyHk9rd2Nfa4EgrKXTAemEquc05XEP4OfKke9U6XZFW+wZ+u85lTzDxcpJIU6pYVz8Ob+ookqtz1FO2+wwTrcM/QckWe6DKPrqHvOAgEZqnr3ALLv8tHGhe5NtNRu9dS54mIbgWrh7T8eO+LNAkyRESfxB1JlqCaxs29KlsGc6i0YYsMwgOTbJNF5boC7Q8pDZ+B9ImIYsLXnUiXAGmZCmfjUwtl8/uzMC73/z+dUhK99Cntg/dYShHQPNbNHL7vxvmMh85I0As3aimDhqdM0ZjRAC04cn9p4dGvtUyVmladgE2te7PZvulzzbthp9tlpM/AgZpSmVj1kgmu99eicUgnOF/kAfZ5RSgmbBn1OM5ewarteSbug6qQkqVvVUq1/W652VSz8UN2KNEujqgo8oBClw6dI4aOGiYtW6rKVpPqKX5mrRk/Ftr6uu+evZ4yF2p6agCYVa3ppwUGHX20jcLIKbE8JzUP6sk0gEX/ybBAdQCMsijqw1BNu14x7pZjsdczF88vSRxjva7NyZs3"
                       + "jl8MySev/OnDalTo8ALZMbNqa/VO2H3IEoyvWX6EcE4TqXAGIw8k6yAnYdQSGz/65UatCtAOWXkOyyXZ72JZdVuY9YzadfjO0aMIu2fuHDRTpm9tfkkhjCQdLfxEsDTifWPA0OpihK6vL97Ya9jMw3UVm1dtHXPPAMCE2GthbGS7GTWrmOrDs2VEe+qBRTx7V/ahWQ68dTi7h+dviGdVmrcEtKfRWADau/KFjkc+uzaOB+kq5y8fimaZ78zvqsUPZXElZZmsWavqvrOa7bsNilVISi1doclg0btPN2zTlS0Nm3L4Bg3DjhPSfAC/kNm9Rd9x7Nw2m/rkhOiYd4ZbVSVn3ZE60O+dZJ6Bf6lpqzjYmDgtRWzKyfNTY9jp8fRojX6miK5WegQ0Rr35Zuwa50lbc1gh4jqIwBMNsxnMX0sF0SwTmPlf2QmjkKVaKXCJvWQBUt2JPwGHcRwT3xqU6xZ0qCdlyL5bTpTqozbEq4wxXQN0KH8iSfBIkp8isvr5WRRniMYpK4qzpxY3ObyU068p0NzHBYVkO2Ln++Mmh/yygqveDmpJshN0vhmr+DJ5XiMUJ+S5PUloz5c12utUEqubBdiWasOQQZIhShiWfakSLPytIfQmoTygMWGG/e3uZ3tOMly1VvPLKcTAszC3nLTZcLz1a/1Ggo5hMYE7tSWMG7P3VC5325zaURb0X8ds6sGkDJiScMP3gp3Hvps6btNMowyyDYFcDEnYXR8EBrooWfpzm+XrIZiH+OWuHXpZxG72eT3EPXfp7+ds/xta1oClcau1omBN/raH75/OQO+UhTei0yBGLFh3G3h2wyu3LxF4Pmv/koHlQdJlpSK7HXEIGidTy1zwhSiLhGFRKWIMCpegCI6v5DjBmYwECj8HIGX+F8gvhKUochY9QHjBr1MVpwpdhuiBNUDMCs3Q/jl53rR5fh3nf13ehQtoJs0m8Gv+W0pZqO0+bw9KfSqyCraZvrJYqmwKW661pivB"
                       + "LRVt4NOF9w6imKEyec198gT9to1j2ERsfkrJMiGR3Oio1uMjpl8Yrd79C3+YUP5UJAAA"; }
        }
    }
}
