// <auto-generated />
namespace WFH.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207221734032_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1ZzW7cNhC+F+g7CDq1BbKykxxSYzeBu7YTo/UPLCc9GrQ0uyZKkQpJGbvP1kMfqa/QoX4oiZJ2tZu4MYpejBU583F+OcPx33/+NX23Spj3CFJRwWf+4eTA94BHIqZ8OfMzvXjxxn/39vvvpqdxsvI+VXSvDB1ycjXzH7ROj4JARQ+QEDVJaCSFEgs9iUQSkFgELw8Ofg4ODwNACB+xPG96k3FNE8g/8HMueASpzgi7EDEwVa7jTpijepckAZWSCGb+72cfJgWV7x0zSlCCENjC99LXRx8VhFoKvgxToilht+sUcH9BmIJS3qP09ViRD14akQPCudAIJ/heKvtWGVTnFNXWayNWrtLMPyHrY/1BJNAkQ8JfYd1awKVrKVKQen0Di5L5/MT3gjZf4DJatgaPOR9/cf3qpe9dZoyRewbWTGjHUAsJ74GDJBria6I1SPT6eQy5/J1TnTPM3+oU9AeGku+d0RXEvwFf6gd70gVZVSv40/c+coqRh0xaZtCUrPjecqjQ//6hoSZSV6eeoLFuaQI9Nm2iTIM6CjbGxnEUCcyTfSIDE0HuEx0VX6HQ+4zGW5RBiEvySJd5fjhgc5GkhGO03ADL99UDTYtsnZS63VmaMymSG8Fqtautu1BkMjKuFf37t0QuQe9p4+r8/7Nvl0QYMu+xUiKiua/bMXzXb+dTHntbnF6o0QgZFDxjmqaMRijBzP+pY49h1CpUGqg2ANuoB5PJoatzQ7tuTGEJ04SizyrF09QswcrN34I8BF1XAFWWAK+2aildXR66SrZhSlVVD4g13BaIwhQU+jCsmRyMhk06stTJ3aAayH833bZHhpW+qXswHqeKhQZOwwBuYrf17EkF6/+6dwmK5qVqcoKBLmd6QdIUs7TR9ZQrXli0PPMX4e6tR1JgBJHq6UCstPYkvHPIEpxdY5IYzqhUGosbuSfm3pjHSYdse7RXB3WCvuuxKvQqFvO7YKt7v8lA49Q0"
                       + "3xlqlOCdmSsHDT9v4M1bTsKI7Lm454JlCR+6/DdxF1dyk79Y2QEh725aCPnKeISyVWlClEtdjGngmNB1UtDxkpMvrt9HRYXN4z1jordhGhURg5xD1qwapaY5+5uub2jP+j7b06ADt/MIgw5yfusEe2pXtAtFb3zXdXFTFNdUI4PV1DrHLAM1r2uUUS6pUPpcY8xiT99dsLKojxRsl+TbKBjWrJjm3eq5Mv2u7Y3Hqe22Bd2A6HQHLokNR9slON3AtKzM2wcjnVJdkPgeav9IY1Omw7XSkEwMwST8zOaMgukLK4ILvCwWoPSt+AOwUcNO4o0zY9lj/hEoFbNnOwShRv+tD65tT+ANLzD+SGT0QOQPCVn9+CUzjS8Cas0pYtRS/5fmFBmnnzOgubsWFOTODmumeCMu9nkCP58Jw3MK7a8/MGjV0F3f8n0Pw/1mDegskMaWhOEdr7TEW77TUlxLyiOaEubI3i13Y2LAWNMiujsnkAI3znWUG3PU5vpukZ2A3GaBHecm3Qfn1vHJmOlJUQvx7rsX6OgiTO12970/MF3ZNFzpO2FoMDEwellvGrz04Q8PLJ5+LuOI3Or6R8xh+gY4TzN26TZQGLSN/z9hzii6rCFMV8ghaoWrpTnnC1FljiNRReLcmBegCVZcciyxOJFI43YESuVj2U+EZUhymtxDfM6vMp1mGlWG5J61jGiyb9P5+WypLfP0Ks1H7l9DBRSTmqbhiv+SURZbuc96moYBCJPWZRkyvtSmHC3XFulS8JFApfnsbXQLScoQTF3xkDzCsGzbbdi22PSEkqUkiSoxan78xPCLk9XbfwAnPdGOQR0AAA=="; }
        }
    }
}
